// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

/*
Package common is a generated protocol buffer package.

It is generated from these files:
	common.proto

It has these top-level messages:
	InvokeServiceRequest
	InvokeServiceResponse
*/
package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// protoc --go_out=plugins=grpc:. common.proto
type InvokeServiceRequest struct {
	ServiceName string `protobuf:"bytes,1,opt,name=serviceName" json:"serviceName,omitempty"`
	MethodName  string `protobuf:"bytes,2,opt,name=methodName" json:"methodName,omitempty"`
	TimeStamp   int64  `protobuf:"varint,3,opt,name=timeStamp" json:"timeStamp,omitempty"`
	Token       string `protobuf:"bytes,4,opt,name=token" json:"token,omitempty"`
	Data        string `protobuf:"bytes,5,opt,name=data" json:"data,omitempty"`
}

func (m *InvokeServiceRequest) Reset()                    { *m = InvokeServiceRequest{} }
func (m *InvokeServiceRequest) String() string            { return proto.CompactTextString(m) }
func (*InvokeServiceRequest) ProtoMessage()               {}
func (*InvokeServiceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *InvokeServiceRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *InvokeServiceRequest) GetMethodName() string {
	if m != nil {
		return m.MethodName
	}
	return ""
}

func (m *InvokeServiceRequest) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *InvokeServiceRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *InvokeServiceRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type InvokeServiceResponse struct {
	Code int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Data string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *InvokeServiceResponse) Reset()                    { *m = InvokeServiceResponse{} }
func (m *InvokeServiceResponse) String() string            { return proto.CompactTextString(m) }
func (*InvokeServiceResponse) ProtoMessage()               {}
func (*InvokeServiceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InvokeServiceResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *InvokeServiceResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *InvokeServiceResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*InvokeServiceRequest)(nil), "common.InvokeServiceRequest")
	proto.RegisterType((*InvokeServiceResponse)(nil), "common.InvokeServiceResponse")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x6b, 0x84, 0x30,
	0x10, 0x85, 0x49, 0xa3, 0x82, 0xd3, 0x1e, 0xca, 0x60, 0x21, 0x87, 0x52, 0xc4, 0x93, 0xa7, 0x5e,
	0xfa, 0x2b, 0x7a, 0x29, 0x34, 0xfe, 0x82, 0x54, 0x87, 0x56, 0x24, 0x19, 0x6b, 0xb2, 0xfe, 0x9e,
	0xfd, 0xa9, 0x8b, 0xc9, 0xb2, 0xca, 0xde, 0xde, 0xfb, 0x78, 0xf3, 0x78, 0x0c, 0x3c, 0xf5, 0x6c,
	0x2d, 0xbb, 0xf7, 0x79, 0xe1, 0xc0, 0x58, 0x24, 0xd7, 0x9c, 0x05, 0x54, 0x9f, 0x6e, 0xe5, 0x89,
	0x3a, 0x5a, 0xd6, 0xb1, 0x27, 0x4d, 0xff, 0x27, 0xf2, 0x01, 0x6b, 0x78, 0xf4, 0x89, 0x7c, 0x19,
	0x4b, 0x4a, 0xd4, 0xa2, 0x2d, 0xf5, 0x11, 0xe1, 0x1b, 0x80, 0xa5, 0xf0, 0xc7, 0x43, 0x0c, 0x3c,
	0xc4, 0xc0, 0x81, 0xe0, 0x2b, 0x94, 0x61, 0xb4, 0xd4, 0x05, 0x63, 0x67, 0x25, 0x6b, 0xd1, 0x4a,
	0xbd, 0x03, 0xac, 0x20, 0x0f, 0x3c, 0x91, 0x53, 0x59, 0x3c, 0x4c, 0x06, 0x11, 0xb2, 0xc1, 0x04,
	0xa3, 0xf2, 0x08, 0xa3, 0x6e, 0xbe, 0xe1, 0xe5, 0x6e, 0xa1, 0x9f, 0xd9, 0x79, 0xda, 0xc2, 0x3d,
	0x0f, 0x69, 0x5b, 0xae, 0xa3, 0xc6, 0x67, 0x90, 0xd6, 0xff, 0x5e, 0xd7, 0x6c, 0xf2, 0x56, 0x29,
	0xf7, 0xca, 0x9f, 0x22, 0x3e, 0xe1, 0xe3, 0x12, 0x00, 0x00, 0xff, 0xff, 0xa7, 0xdb, 0xc9, 0x54,
	0x14, 0x01, 0x00, 0x00,
}
